In [1]:
import pandas as pd

In [35]:
df = pd.read_csv("/Users/abhishek/Documents/Project_830/Data/control.csv", header=1)
df.head(15)

,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,User Language,Age,Gender,How often do you shop online?,How important are “Limited Edition” products to you? - Choose:Right,How much You willing to pay - Us $,How much you are willing to pay - Us $,How much you are willing to pay - Us $.1,How much you are willing to pay - Us $.2,How much you are willing to pay - Us $.3
0,"{""ImportId"":""startDate"",""timeZone"":""Z""}","{""ImportId"":""endDate"",""timeZone"":""Z""}","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""Z""}","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}",...,"{""ImportId"":""userLanguage""}","{""ImportId"":""QID5""}","{""ImportId"":""QID4""}","{""ImportId"":""QID8""}","{""ImportId"":""QID12_1""}","{""ImportId"":""QID16_1""}","{""ImportId"":""QID18_1""}","{""ImportId"":""QID20_1""}","{""ImportId"":""QID24_1""}","{""ImportId"":""QID22_1""}"
1,2026-02-13 02:42:43,2026-02-13 02:44:21,1,NaN,100,98,1,2026-02-13 02:44:21,R_3TJYd3ZkDqxNCsF,NaN,...,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-02-13 04:08:08,2026-02-13 04:09:12,1,NaN,100,63,1,2026-02-13 04:09:12,R_1KYAQ68yuP1nbc5,NaN,...,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-02-13 15:54:08,2026-02-13 15:54:32,1,NaN,100,24,1,2026-02-13 15:54:35,R_3LcEQ68CnM5EaxJ,NaN,...,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-02-13 15:55:50,2026-02-13 15:56:09,1,NaN,100,18,1,2026-02-13 15:56:09,R_3nGTNhqlvMXRZP0,NaN,...,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2026-02-13 16:46:23,2026-02-13 16:47:17,1,NaN,100,53,1,2026-02-13 16:47:17,R_1npfqTJcetbP2qO,NaN,...,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
6,2026-02-13 17:03:18,2026-02-13 17:54:11,1,NaN,100,3052,1,2026-02-13 17:54:12,R_3QzGsqB61jrxU0F,NaN,...,EN,2,NaN,1,2,62,69,62,62,49
7,2026-02-13 17:54:15,2026-02-13 17:54:32,1,NaN,100,17,1,2026-02-13 17:54:33,R_3EHYA5a1HmA2oPD,NaN,...,EN,3,NaN,3,3,40,41,49,55,53
8,2026-02-13 17:54:35,2026-02-13 17:54:59,1,NaN,100,24,1,2026-02-13 17:55:00,R_32aGTQyahiqOmQP,NaN,...,EN,2,4,3,2,65,68,50,69,30
9,2026-02-13 17:55:02,2026-02-13 17:55:24,1,NaN,100,22,1,2026-02-13 17:55:25,R_3jNdu3373Leb3vN,NaN,...,EN,1,2,2,1,21,16,27,34,32
10,2026-02-13 17:55:31,2026-02-13 17:55:53,1,NaN,100,22,1,2026-02-13 17:55:54,R_39H3cBYvGCmraQ9,NaN,...,EN,4,2,2,5,31,30,27,37,43

In [36]:
df = pd.read_csv("/Users/abhishek/Documents/Project_830/Data/treatment_clean.csv", header=1)
df.head(15)

,"{""ImportId"":""startDate"",""timeZone"":""Z""}","{""ImportId"":""endDate"",""timeZone"":""Z""}","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""Z""}","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}",...,"{""ImportId"":""QID5""}","{""ImportId"":""QID4""}","{""ImportId"":""QID8""}","{""ImportId"":""QID12_1""}","{""ImportId"":""QID16_1""}","{""ImportId"":""QID18_1""}","{""ImportId"":""QID20_1""}","{""ImportId"":""QID24_1""}","{""ImportId"":""QID22_1""}",1
0,2026-02-13 17:47:19,2026-02-13 17:48:05,1,NaN,100,46,1,2026-02-13 17:48:06,R_3whQcOKLKrRChcL,NaN,...,2,1,3,3,10,50,80,70,80,1
1,2026-02-13 17:48:15,2026-02-13 17:48:49,1,NaN,100,34,1,2026-02-13 17:48:49,R_3gI5E345rXqI8cZ,NaN,...,3,1,2,4,92,11,85,83,61,1
2,2026-02-13 17:51:37,2026-02-13 17:52:04,1,NaN,100,27,1,2026-02-13 17:52:04,R_3kS8gRyuwG6jqVY,NaN,...,4,2,2,3,49,33,46,55,56,1
3,2026-02-13 17:52:08,2026-02-13 17:52:28,1,NaN,100,20,1,2026-02-13 17:52:29,R_3EYjSGulk8I3uce,NaN,...,4,2,3,2,57,49,50,50,31,1
4,2026-02-13 17:52:31,2026-02-13 17:53:00,1,NaN,100,28,1,2026-02-13 17:53:00,R_3jZoMVhezxtNxmW,NaN,...,5,1,2,5,28,60,100,100,64,1
5,2026-02-13 17:53:02,2026-02-13 17:53:27,1,NaN,100,25,1,2026-02-13 17:53:28,R_3KNJTC3O6oJRTFv,NaN,...,3,2,2,4,28,21,87,83,82,1

In [29]:
df = pd.read_csv("/Users/abhishek/Documents/Project_830/Data/combined.csv", header=1)
df.head(15)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,"{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}",Unnamed: 7,Unnamed: 8,Unnamed: 9,...,"{""ImportId"":""QID5""}","{""ImportId"":""QID4""}",Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,0
0,NaN,NaN,NaN,NaN,100,98,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,NaN,NaN,NaN,NaN,100,63,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,NaN,NaN,NaN,NaN,100,24,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,NaN,NaN,NaN,NaN,100,18,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,NaN,NaN,NaN,NaN,100,53,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5,NaN,NaN,NaN,NaN,100,3052,1,NaN,NaN,NaN,...,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
6,NaN,NaN,NaN,NaN,100,17,1,NaN,NaN,NaN,...,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
7,NaN,NaN,NaN,NaN,100,24,1,NaN,NaN,NaN,...,2,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
8,NaN,NaN,NaN,NaN,100,22,1,NaN,NaN,NaN,...,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
9,NaN,NaN,NaN,NaN,100,22,1,NaN,NaN,NaN,...,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
10,NaN,NaN,NaN,NaN,"{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}",NaN,NaN,NaN,...,"{""ImportId"":""QID5""}","{""ImportId"":""QID4""}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
11,NaN,NaN,NaN,NaN,100,46,1,NaN,NaN,NaN,...,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
12,NaN,NaN,NaN,NaN,100,34,1,NaN,NaN,NaN,...,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
13,NaN,NaN,NaN,NaN,100,27,1,NaN,NaN,NaN,...,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
14,NaN,NaN,NaN,NaN,100,20,1,NaN,NaN,NaN,...,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1